### ISSUE TITLE
Remove 'locatives' from trace.clj

### ISSUE THREAD

**Issue by jar600** [probcomp/metaprob-clojure#26]
They are no longer needed, if PR #25 is merged.

**Comment by jar600** [comment]
I think @vkmvkmvkmvkm is reluctant to remove the locative-based side-effecty interpreter? Not sure how to resolve. I'll leave this issue with a 'question' label until he weighs in.

**Comment by vkmvkmvkmvkm** [comment]
Let's remove this locative-based side-effecty interpreter.

Vikash

**Comment by zane** [comment]
If #44 fixed this should this be closed?
