### ISSUE TITLE
Makefile fails in parse-all

### ISSUE THREAD

**Issue by rpgoldman** [probcomp/metaprob-clojure#34]
When I try to build metaprob-clojure on my Mac (in `~/src/metaprob-clojure`) I get this error:

```
$ make
bash bin/parse-all
find: ‘metacirc’: No such file or directory
make: *** [Makefile:3: all] Error 1
```

`parse-all` tries to `cd` to `../metaprob`, so is the Makefile making an assumption about us also having some other metaprob repository checked out?  If so, will you please add this to the installation instructions?

**Comment by jar398** [comment]
What are you trying to do?  There is no build step, you just use lein to load it into clojure. Documentation is here: https://github.com/probcomp/metaprob-clojure/blob/master/INSTALL.md

**Comment by jar398** [comment]
I guess I can change the `Makefile` so that the default rule prints out some kind of message rather than producing an error.

**Comment by rpgoldman** [comment]
Got it, now I see.  I have only the most glancing familiarity with clojure, and less with its ecosystem, so I didn't realize that `lein` would do all I want, so I just started by doing `make`, since there was a Makefile.
