### ISSUE TITLE
Should we make master a protected branch?

### ISSUE THREAD

**Issue by zane** [probcomp/metaprob-clojure#68]
GitHub has a feature called "[protected branches](https://help.github.com/articles/about-protected-branches/)". They describe it as follows:

> Protected branches ensure that collaborators on your repository cannot make irrevocable changes to branches. Enabling protected branches also allows you to enable other optional checks and requirements, like required status checks and required reviews.
> 
> Repository owners and people with admin permissions for a repository can enforce certain workflows or requirements, before a collaborator can merge a branch in your repository by creating protected branch rules.
> 
> — [About protected branches - User Documentation](https://help.github.com/articles/about-protected-branches/)

Here is the full list of available [branch protection settings](https://help.github.com/articles/about-protected-branches/#branch-protection-settings).

**Comment by jar398** [comment]
Seems heavyhanded. In 5 years on the open tree project I never felt a need for this. As far as I can remember nothing bad ever happened that would have been prevented by any of these five checks, and the checks would have all been annoying at least once.

But I would listen to a case for this, for metaprob particularly, at any point.

**Comment by jar398** [comment]
@zane what has your experience with this feature been?

**Comment by zane** [comment]
@jar398 I use it on all my projects and have never found it annoying, but my usage patterns might be different from yours! 

The settings I would be interested in are these two:

1. Can't merge changes into the protected branch unless [required status checks](https://help.github.com/articles/about-required-status-checks/) pass.
2. Can't edit the protected branch or upload files to it from the web.

`(1)` seems appealing to me because it's hard for me to imagine a situation where we wouldn't want to wait for the Travis build to succeed before merging a branch down to `master`.

As for `(2)`, I'm always a _little bit_ anxious that I or someone else might accidentally do something catastrophic like delete `master` (or force push to it). As the set of contributors grows that anxiety will only increase. 😅

**Comment by jar398** [comment]
Happy to give it a try. While I've never felt a need, I also can't recall a situation where this would have gotten in the way. So no objection.

**Comment by zane** [comment]
Okay. I've added branch protection for `master`.
